version: '3.7'

services:
  grafana-renderer:
    image: ${IMAGE_NAME:-grafana/grafana-image-renderer}:${IMAGE_TAG:-latest}
    environment:
      ENABLE_METRICS:
      BROWSER_TZ:
      HTTP_PORT:
    networks:
      monitoring-net:
      traefik-net:
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-10s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-512M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-128M}

networks:
  monitoring-net:
    name: ${MONITORING_NET_NAME:-monitoring-net}
    driver: ${MONITORING_NET_DRIVER:-overlay}
    external: true

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true
